name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    # Run the tests for all OSs and EMACS_VERSIONs.
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        emacs_version: ['28.2', '29.1']

    steps:
    - name: Setup dev env (MS-Windows)
      uses: msys2/setup-msys2@v2
      if: startsWith (matrix.os, 'windows')
      with:
        msystem: MINGW64
        location: D:\
        pacboy: >-
          gcc:p sqlite3:p

    - name: Set up Emacs
      if: "!startsWith (matrix.os, 'windows')"
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Set up Emacs (MS-Windows)
      if: startsWith (matrix.os, 'windows')
      uses: jcs090218/setup-emacs-windows@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      if: "!startsWith (matrix.os, 'windows')"
      run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

    - name: Install Eldev (MS-Windows)
      if: startsWith (matrix.os, 'windows')
      run: |
        # Remove expired DST Root CA X3 certificate. Workaround
        # for https://debbugs.gnu.org/cgi/bugreport.cgi?bug=51038
        # bug on Emacs 27.2.
        gci cert:\LocalMachine\Root\DAC9024F54D8F6DF94935FB1732638CA6AD77C13
        gci cert:\LocalMachine\Root\DAC9024F54D8F6DF94935FB1732638CA6AD77C13 | Remove-Item

        curl.exe -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev.bat | cmd /Q

    - name: Check out the source code
      uses: actions/checkout@v3

    - name: Test
      if: "!startsWith (matrix.os, 'windows')"
      env:
        # purcell/setup-emacs releases are built with nix and as such
        # we need to build the api with nix for binary compatibility.
        SQLITE3_API_BUILD_COMMAND: "nix-shell -p sqlite.dev --run \"make all\""
      run: |
        eldev -p -dtTC test

    - name: Test (MS-Windows)
      if: startsWith (matrix.os, 'windows')
      run: |
        # Update PATH to include first to the new msys2 dev
        # environment.
        $env:Path = "D:\msys64\mingw64\bin;" + $env:Path
        #
        eldev -p -dtTC test
